name: linter

on:
  push
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '15 6 * * *'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ansible-vault-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ansible-vault-${{ runner.os }}-
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: tomoh1r/ansible-vault/.github/actions/lint-it@master
